# =========================
# DATASOURCE CONFIG
# =========================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=yohanes12
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/taksol_db

# =========================
# HIBERNATE
# =========================
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

mp.jwt.verify.issuer=taksol-app
quarkus.smallrye-jwt.enabled=true
quarkus.http.auth.proactive=false

mp.jwt.verify.publickey.location=keys/publicKey.pem
smallrye.jwt.sign.key.location=keys/privateKey.pem
smallrye.jwt.sign.algorithm=RS256

quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.start-tls=DISABLED
quarkus.mailer.from=no-reply@taksol.com
quarkus.mailer.mock=false

midtrans.server-key=SB-Mid-server-IR89_N281ir4GtjUPdmjkc43
midtrans.client-key=SB-Mid-client-MpjrZ332AjA_LRzn
midtrans.is-production=false

google.maps.api.key=AIzaSyDSCI7ovOI4lofG-iSvEn32KDvWSND6TOM
google.maps.base.url=https://maps.googleapis.com
quarkus.rest-client.google-maps.url=${google.maps.base.url}
quarkus.rest-client.google-maps.scope=jakarta.inject.Singleton


